// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsvkjctkcftekucvqpdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzdmtqY3RrY2Z0ZWt1Y3ZxcGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTUwODMsImV4cCI6MjA2NzYzMTA4M30.7URHP3gpdSsIyWYpw0El9NdYTVy4YNLtiJZNAexjlmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});