// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfuiclfpsdpowlkcsbaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmdWljbGZwc2Rwb3dsa2NzYmF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODAxNDYsImV4cCI6MjA2ODM1NjE0Nn0.fEC5VG1ooSDBdl7VDim2LV70EW0tPhNNtgcbBHAp8U4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});